### ISSUE TITLE
Make category endpoint return custom attributes

### ISSUE THREAD

**Issue by leonvisscher** [deity-io/falcon-magento2-development#102]
**Is your feature request related to a problem? Please describe.**
The `[GET] /V1/falcon/categories/:categoryId/products` endpoint does not return custom attributes. I'd like this to be possible so I can use custom attributes in the product listing.

**Describe the solution you'd like**
For `[GET] /V1/falcon/categories/:categoryId/products` to return custom attributes

**Describe alternatives you've considered**
I've considered using the falcon products query (which uses the default `/V1/products/...` endpoint) but here the absolute url paths to cached thumbnail images arent available, which isnt ideal.

**Comment by sergy-gzh** [comment]
Hi @leon0v!
Have you tried to add your custom attributes to `extension_attributes` of `Deity\CatalogApi\Api\Data\ProductInterface` ?
You can checkout how its done here:
https://github.com/deity-io/falcon-magento2-development/blob/develop/app/code/Deity/Catalog/etc/extension_attributes.xml
https://github.com/deity-io/falcon-magento2-development/blob/develop/app/code/Deity/Catalog/Plugin/ProductConvertPluginExample.php

**Comment by schmengler** [comment]
Extension attributes with all their overhead for all custom attributes, that usually are not even created programmatically but via admin or import, and only needed for frontend purposes? That's possible, but indeed not ideal. Is there a reason not to include custom attributes?

**Comment by sergy-gzh** [comment]
Hi @schmengler 
I discovered that we are not using any of the `custom_attributes` (full list can we see in PDP API) is used on Falcon side.
Attributes that are marked as `used_in_product_listing` are not needed at Falcon frontend.
Same goes for filterable attributes.
In the end what is really needed for product display withing the listing page can be put into the Product Data Model.
