### ISSUE TITLE
Provide "canonical" URL data for product/category

### ISSUE THREAD

**Issue by sergy-gzh** [deity-io/falcon-magento2-development#2]
@Borales commented on [Thu Oct 11 2018](https://github.com/deity-io/falcon-magento2-module/issues/6)

**Is your feature request related to a problem? Please describe.**
To improve SEO behavior - we need to get "canonical" URL data for Magento entities, so on the front-end side we would provide `<link rel="canonical" href="${canonicalUrl}" />` meta-tag so search-engines would properly parse the page and won't save it as a duplicate content with a different URL.

**Describe the solution you'd like**
Provide `canonicalUrl` property for product and category.

**Comment by sergy-gzh** [comment]
Hi @ryan-copeland!
We already have a field for it in our `UrlRewrite API`
Sample response:
`
{
   "entity_type": "CATEGORY",
   "entity_id": "4",
   "canonical_url": "catalog/category/view/id/4"
}
`

Now it returns `target_path`, should return a proper canonical URL. Like `woman.html` or `woman/shoe.html`. Including url suffix (if applied)

**Comment by ryan-copeland** [comment]
Hi @sergy-gzh, how do you pass the URL to the end point /V1/url?

**Comment by ryan-copeland** [comment]
When applying this feature I explored the \Magento\Framework\View\Page\Config::addRemotePageAsset function and this doesn't seem to provide any logic around generating the canonical URL. It only adds the canonical tag to the head using the URL provided. 

The category canonical URL is always just the base URL with the request path appended. For products this works in a slightly different way as the category path is ignored when generating the URL.

**Comment by sergy-gzh** [comment]
#39
