### ISSUE TITLE
Cart is not merged correctly when user logs in

### ISSUE THREAD

**Issue by mateuszwozniak** [deity-io/falcon-magento2-development#23]
**Describe the bug**
If a user has some items in cart and logs in then the cart is not merged correctly.

**To Reproduce**
1. Sign in
2. Add item A to cart
3. Sign out
4. Add item B to cart (now you have only item B in cart)
5. Sign in again
6. The content of your cart (item B) gets removed - you have only item A. 

That's incorrect as usually users add items as guests and then they log in on the checkout page. Currently, such actions will remove all the items added before they log in.

**Expected behavior**
Items should not be removed from cart upon sign in - either items added as a guest should be used or these items should be merged with user's preserved cart.

**Comment by php4umagento** [comment]
@mateuszwozniak what exact magento version was used? Are you talking about magento frontend or rest API?

**Comment by mateuszwozniak** [comment]
That happens on v2.2 in rest API. We'll test that on 2.3 soon as we're tweaking our middleware to work with 2.3 and our latest changes in magneto module.
