### ISSUE TITLE
Add token lifetime for customer and admin to storeConfig data

### ISSUE THREAD

**Issue by sergy-gzh** [deity-io/falcon-magento2-development#32]
**Describe the bug**
We need to provide values of customer/admin token lifetime to Falcon.

**To Reproduce**
After removing customizations for customer token, these information is not getting sent over.
**Expected behavior**
Token lifetime should be shared with the rest of store info.
API request path: `rest/default/V1/store/storeConfigs`.
Changes should be placed in `Deity_Store` namespace

**Additional context**
Customer token lifetime is stored in `oauth/access_token_lifetime/customer`
admin -> `oauth/access_token_lifetime/admin`

**Comment by ryan-copeland** [comment]
Token lifetime should be returned with the following response.

`rest/default/V1/store/deityStoreConfigs`
