### ISSUE TITLE
New search API

### ISSUE THREAD

**Issue by sergy-gzh** [deity-io/falcon-magento2-development#36]
**What should be changed/improved?**
Introduce new API to render search results for products
**Your suggested solution**
Search result page should provide response similar to `/V1/categories/:categoryId/products` API.
**Input**
- As an input param instance of `Magento\Framework\Api\SearchCriteriaInterface` can be used.
- To utilize search functions use `search_term` field.
- provide extra param to ommit filter data from response (in case of quick search field)
**Output**
- API should return instance of `Deity\CatalogApi\Api\Data\ProductSearchResultsInterface` or similar interface.
** Use cases **
- Provide product listing + filters on search page
- Provide product info in quick search dropdown
- Provide product listing info for homepage (based on filter)

Make use of CatalogSearch Layer.

**Comment by php4umagento** [comment]
@sergy-gzh - have you seen - vendor/magento/module-search/etc/webapi.xml

```
<route url="/V1/search" method="GET">
        <service class="Magento\Search\Api\SearchInterface" method="search"/>
        <resources>
            <resource ref="anonymous" />
        </resources>
    </route>
```

**Comment by php4umagento** [comment]
@sergy-gzh - looks like it is gonna be a proper battle to get layered navigation filters in search results....

**Comment by sergy-gzh** [comment]
@php4umagento 
I would consider a different approach.
Take a look at this method:
`Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionTest::testSearchResultsAreTheSameForSameRequests`
Here search query is set using special key `search_term` through existing filter API. 
I think we can reuse same interface and provide similar response data as on product listing page.

**Comment by php4umagento** [comment]
Thanks, that might be it. Let me review it
