### ISSUE TITLE
Selected aggregations must be sent back to the client

### ISSUE THREAD

**Issue by mateuszwozniak** [deity-io/falcon-magento2-development#72]
Problem:
Magento doesn't send back already selected aggregations so there's no way of showing what filters are selected on the frontend. We can save aggregations received in the previous step and use it later but that doesn't fix the issue when you e.g. send a link to someone - filters will be applied correctly in his browser (parsed from url) but there's no way of showing which filters are applied - we have only field and value, but we don't have names (and amounts).

Proposed solution:
The preferred way would be to simply include selected values in the aggregations response, meaning that arrays with aggregations in  `aggregations` property would also contain selected buckets. That way we could simply mark selected values on filters panel - that's the best UX.

Another solution would be to send information about selected aggregations in a separate property but it would have to contain also all the details needed on UI (so the same what we get in aggregations).

**Comment by sergy-gzh** [comment]
Selected values are included in aggregation response as suggested.
Sample:
```
{
            "label": "Climate",
            "code": "climate",
            "options": [
                {
                    "label": "All-Weather",
                    "value": "204",
                    "count": 0,
                    "is_selected": true
                }
]
}
```
`is_selected` flag added.
Selected items are added at the beginning.
