### ISSUE TITLE
Subcategory filters do not work

### ISSUE THREAD

**Issue by mateuszwozniak** [deity-io/falcon-magento2-development#73]
**Describe the bug**
Sending filter with field set to `cat` and value to one of the values returned by Magento in `aggregations` doesn't filter correctly by passed filter.
For example this url:
```
https://magento.deity.io/rest/default/V1/categories/24/products
?searchCriteria[filterGroups][0][filters][0][condition_type]=eq
&searchCriteria[filterGroups][0][filters][0][field]=cat
&searchCriteria[filterGroups][0][filters][0][value]=26
&searchCriteria[sortOrders][0][field]=price
&searchCriteria[sortOrders][0][direction]=asc
&searchCriteria[currentPage]=0
&searchCriteria[pageSize]=20
```
Should return products from `Women > Tops` that are assigned to `Jackets` category but it returns all the results from `Women > Tops`

**Expected behavior**
Magento should filter products by passed subcategory

**Comment by sergy-gzh** [comment]
Resolved in upcomming release
