### ISSUE TITLE
Product price in cart for logged-in users

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon-magento2-development#83]
**Describe the bug**
After adding a product to the cart (I tested homepage products) while being logged in - cart shows "Price: 0". When you add a second product - price shows correctly for both products.

**To Reproduce**
1. Go to homepage
2. Click on any product from the homepage
3. Select any combination and click "add to cart"
4. Price in the cart should be 0
5. Add second product - price should be correct for both products

**Screenshots**
<img width="1500" alt="Screenshot 2019-03-19 at 16 44 30" src="https://user-images.githubusercontent.com/1118933/54621544-32bfde00-4a68-11e9-8a69-7998ce3f4000.png">

<img width="1183" alt="Screenshot 2019-03-19 at 16 59 07" src="https://user-images.githubusercontent.com/1118933/54621626-56832400-4a68-11e9-8b7d-99a376ede646.png">

**Comment by cane-lagerwaard** [comment]
@Borales @sergy-gzh This does not only happen when a visitor is logged in. Note: it doesn't appear to happen with products in the "training" category

**Comment by Borales** [comment]
Bug updates:
- after adding your first product to the cart with "Price: 0" - you can"trigger" the price by changing the "amount" field
- the price fixes itself when you go through the checkout and select your "shipping method"

**Comment by Borales** [comment]
https://github.com/deity-io/falcon/issues/443 looks like the issue remains active
