### ISSUE TITLE
No data is pulled from AWS EC2 hosted magento store after changing the api to reflect my own store.

### ISSUE THREAD

**Issue by M65D85** [deity-io/falcon-magento2-development#85]
I am not getting any data back from my magento store which is hosted on an aws instance. 

I ran composer require deity/falcon-magento ^3.0.0 module and ran bin/magento setup:upgrade as well. Then created an admin user account for falcon and used that user in the default.json file.

I have also changed the hard corded category ID-25  on the src/pages/Home.js to the valid category ID-2 in my magento store.

Below are the screenshots of all the error reports and the magento log file.

To reproduce the behavior:
1. Changed the api to my magento store in /server/config/default.json 
2. Changed the Category ID-25 to Category ID-2 in src/pages/Home.js
3. Refreshed the index page

I was expecting to get data from the server as there are products listed on the store under the category id listed.

This is the index page.
![index](https://user-images.githubusercontent.com/34279492/54876944-35db1580-4e3e-11e9-95ca-e93a23e3cb9f.JPG)

This is the client side error when trying to load the index page.  
![client_side](https://user-images.githubusercontent.com/34279492/54876832-936e6280-4e3c-11e9-8b65-da4a4d4f9838.JPG)

On the server side, this is the error: 
![server_side](https://user-images.githubusercontent.com/34279492/54876842-c31d6a80-4e3c-11e9-9df9-f68472bb966a.JPG)

The magento log file: 
![exception_log](https://user-images.githubusercontent.com/34279492/54876928-06c4a400-4e3e-11e9-8b50-8e2af699885c.JPG)

Desktop :
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [72.0.3626.121]

**Comment by sergy-gzh** [comment]
Hi @M65D85 !
Thank you for your extensive report. I will take a look at the issue

**Comment by M65D85** [comment]
> Hi @M65D85 !
> Thank you for your extensive report. Seems like you don't have any categories to display in the menu.
> I will take a look at the issue

Hi @sergy-gzh !
Yes you are absolutely right. Thank you for this clarification. I was under the impression that the products listed in the default category will still be returned. But I see that the parameter is category based.

Thank you!
